CREATE TABLE teleskop_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    token VARCHAR(255) NULL DEFAULT NULL
);

CREATE TABLE file_data (
    id CHAR(36) PRIMARY KEY,
    user_id INT NOT NULL,
    fileName VARCHAR(255) NOT NULL,
    fileType VARCHAR(255) NOT NULL,
    fileSize BIGINT NOT NULL,
    file LONGBLOB NOT NULL,
    hidden_file BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (user_id) REFERENCES teleskop_users(id)
);